###### MAPS Project: Density Dependence #######
### Script name: FigureS1.R
### Author(s): SLJ

########### Objective/Description of Script #####################
# create Figure S1, which one panel for each species
# each panel depicts the predicted productivity-abundance relationship for a species across all stations
# and also includes a subset of station-level random slopes and intercepts
#################################################################

### Setup ###

library(here)
library(tidyverse)
library(brms)
library(colorspace)
library(ggforce)
library(ggdist)

#################################################################

# import models from previous script
m2_allspp_loo <- readRDS(here("Models", "m2_allspp_loo.rds"))

# make an object that only contains the models
m2_onlymodels <- m2_allspp_loo %>% select(SPEC, m2)
rm(m2_allspp_loo) # remove large object from environment

# import list of species with names and classifications of curve type and the MAPS stations for each species
SppNames_STA <- readRDS(here("Outputs", "SppNames_STA.rds"))

# obtain subset of stations to plot for each species
STAlist <- SppNames_STA %>% 
  select(SPEC, STA) %>%
  group_by(SPEC) %>%
  slice_head(n = 15) %>% 
  nest() %>%
  rename(STAlist = data)

# get data for conditional effects plots for station-level random effects
# note: this step is time consuming and requires downloading and importing a large file (m2_allspp_loo.rds)
# you can skip this step and import the output generated by it below
STA_RE_m2 <- m2_onlymodels %>%
  left_join(., STAlist) %>%
  mutate(
    RE_CE = map2(m2, STAlist,
                 ~conditional_effects(.x, re_formula=~(1+Adult|STA), 
                                      conditions= .y, prob=0)),
    RE_CE_df = map(RE_CE, ~data.frame(.x[[1]]))) %>% # extract the data object generated by conditional_effects and save as a df for plotting
  select(-m2)

#saveRDS(STA_RE_m2, here("Outputs", "STA_RE_m2.rds"))
STA_RE_m2 <- readRDS(here("Outputs", "STA_RE_m2.rds")) # import results from previous step

# extract data for adding station-level random effects to plots
RE_m2_df <- STA_RE_m2 %>% 
  pull(RE_CE_df, name=SPEC) %>% 
  bind_rows(., .id="SPEC") 

# get identifying info for each plot
plotinfo <- SppNames_STA %>% 
  select(SPEC, COMMONNAME, Curve_type) %>%
  distinct()

# add identifiers to random effects plot data
RE_m2_plotdat <- left_join(RE_m2_df, plotinfo) %>%
  select(SPEC, STA, Adult, estimate__, COMMONNAME, Curve_type)

# import data from previous step for plotting species-level conditional effects
FE_m2_plotdf <- readRDS(here("Outputs", "epred_df_m2.rds"))

# add some identifying info (common name for species, classification for shape of curve)
FE_m2_plotdat <- left_join(FE_m2_plotdf, plotinfo) %>%
  select(SPEC, COMMONNAME, Curve_type, Adult, .epred)

# plot data for the abundance-productivity relationship for each species and the station-level random effects
plots_bothRE_FE <- 
  ggplot(data = FE_m2_plotdat, aes(x = Adult, y = .epred)) + 
  stat_lineribbon(color = "#1874CD") +
  scale_fill_manual(values = colorspace::lighten("#1874CD", c(0.95, 0.75, 0.5))) +
  guides(fill = "none") +
  labs(x = "Adult Abundance", y = "Predicted Productivity") +
  theme_classic() +
  geom_line(data = RE_m2_plotdat, 
            aes(x = Adult, y = estimate__, group = STA),
            color = "gray40", linewidth = 0.5, alpha=0.2) +
  theme(strip.background = element_rect(color=NA), # remove border around plot title
        strip.text = element_text(size=14, , family="Arial"),
        axis.title = element_text(size=14, family="Arial"),
        axis.text = element_text(size=11, family="Arial"))
    

# print onto multiple pages 
# two columns and three rows of plots for each page
plots_bothRE_FE + facet_wrap_paginate(~COMMONNAME, scales="free", nrow = 3, ncol = 2, page = 8) # view page 1


